# Generated by Django 4.2.2 on 2023-06-27 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronym', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_username', models.CharField(max_length=255)),
                ('telegram_id', models.CharField(max_length=255)),
                ('phone_numbers', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('region', models.CharField(choices=[('region1', 'Край 1'), ('region2', 'Край 2'), ('region3', 'Край 3')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district_city', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='student_photos')),
                ('otp_token', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=32, null=True)),
                ('language', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
