# Generated by Django 4.2.2 on 2023-06-22 09:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronym', models.CharField(blank=True, max_length=50)),
                ('info', models.TextField()),
                ('photo', models.ImageField(upload_to='professors/')),
                ('tg_username', models.CharField(max_length=50)),
                ('tg_idbot', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('price', models.JSONField()),
                ('language', models.CharField(max_length=50)),
                ('experience', models.CharField(choices=[('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', 'More than 10 years')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
