# Generated by Django 4.2.2 on 2023-06-22 10:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, size=None)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professors')),
            ],
        ),
    ]
