# Generated by Django 4.2.2 on 2023-07-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_professors_user_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='price',
            field=models.JSONField(null=True),
        ),
    ]
