# Generated by Django 4.2.2 on 2023-07-03 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_alter_professors_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='patronym',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='rate',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
