# Generated by Django 4.2.2 on 2023-07-03 05:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_alter_professors_patronym_alter_professors_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='friday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='monday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='saturday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sunday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thursday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tuesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wednesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, default=list, null=True, size=None),
        ),
    ]
