# Generated by Django 4.2.2 on 2023-07-03 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_alter_timetable_friday_alter_timetable_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='price',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='professors',
            name='tg_idbot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
