# Generated by Django 4.2.2 on 2023-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_alter_professors_price_alter_professors_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='professors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='professors/'),
        ),
    ]
