# Generated by Django 4.2.2 on 2023-06-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_professors_user_timetable'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting',
            new_name='Meetings',
        ),
    ]
