# Generated by Django 4.2.2 on 2023-06-27 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_rename_meeting_meetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
